---
apiVersion: v1
kind: Namespace
metadata:
  name: '{{ .Values.cluster.name }}'
  annotations:
    openshift.io/description: 'Namespace representing managed cluster {{ .Values.cluster.name }}'
    openshift.io/display-name: '{{ .Values.cluster.name }} Cluster'